version: '3.5'

services:
  mongodb:
    container_name: mongo_container
    image: mongo:4.2.5
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb
    restart: unless-stopped
  mongoku:
    container_name: monuku_container
    image: huggingface/mongoku:1.3.0
    ports:
      - "3100:3100"
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://mongodb:27017
    networks:
      - mongodb
    depends_on:
      - mongodb
networks:
  mongodb:
    driver: bridge

volumes:
    mongodb_data_container:
