version: '3.5'

services:
  mongodb:
    container_name: mongodb_container
    image: mongo:4.2.5
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb
    restart: unless-stopped
  

networks:
  mongodb:
    driver: bridge

volumes:
    mongodb_data_container:
